name: Alessandro Pellegrini
markdown: kramdown
highlighter: pygments
exclude: [README.md, pubs.bib, LICENSE, upload.sh]

url: "https://www.alessandropellegrini.it/"

# Blog posts map to courses
permalink: /didattica/:year/:title.html

# Static pages (to reduce generation time for abstracts of papers)
collections:
  main_pages:
    output: true

plugins: 
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-regex-replace
scholar:
  style: _layouts/custom.csl
  source: ./
  bibliography: pubs.bib
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending
  details_dir: publications
  details_layout: bibpage.html
  details_link: DetailsToRemove
  repository: publications
  bibliography_template: bibliography
  bibliography_list_tag: div
  bibliography_item_tag: div
  reference_tagname: 
